pull_request_rules:
  - name: Automatically merge GreenKeeper PRs if tests pass
    conditions:
      - author=greenkeeper[bot]
      - status-success="ci/circleci: build"      
    actions:
      merge:
        method: merge