pull_request_rules:
  - name: automatic merge of greenkeeper PRs to develop branch
    conditions:
      - 'status-success=ci/circleci: build'
      - 'base=develop'
      - 'author=snyk-bot'
    actions:
      merge:
        method: merge
