pull_request_rules:
  - name: automatic merge of greenkeeper PRs to develop branch
    conditions:
      - 'status-success=ci/circleci: build'    
      - 'base=develop'
      - 'author=app/greenkeeper'
    actions:
      merge:
        method: merge