export const UNEXPECTED = 'UNEXPECTED';
export const INVALID_CONFIGURATION = 'INVALID_CONFIGURATION';
export const USER_INTERUPTION = 'USER_INTERUPTION';
export const NOT_FOUND = 'NOT_FOUND';
export const CORRUPTED_FILE = 'CORRUPTED_FILE';
export const PATH_ALREADY_EXISTS = 'PATH_ALREADY_EXISTS';
