version: 2
jobs:
  build:
    docker:
      - image: node:8.11.3

    working_directory: /tmp/fbl

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install app dependencies and build app
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests and generate coverage report
      - run: yarn test

      # generate coverage report
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov > /tmp/fbl/coverage.lcov

      # send test coverage
      - run: bash <(curl -s https://codecov.io/bash) -f /tmp/fbl/coverage.lcov
