import * as Joi from 'joi';
import {FBL_ASSIGN_TO_OBJECT_SCHEMA, FBL_ASSIGN_TO_STRING_SCHEMA} from './assignTo';

const FBL_PUSH_TO_OBJECT_SCHEMA = FBL_ASSIGN_TO_OBJECT_SCHEMA.keys({
    children: Joi.boolean()
});

const FBL_PUSH_TO_STRING_SCHEMA = FBL_ASSIGN_TO_STRING_SCHEMA;

const FBL_PUSH_TO_SCHEMA = Joi.alternatives(
    FBL_PUSH_TO_OBJECT_SCHEMA,
    FBL_PUSH_TO_STRING_SCHEMA
);

export {
    FBL_PUSH_TO_OBJECT_SCHEMA,
    FBL_PUSH_TO_STRING_SCHEMA,
    FBL_PUSH_TO_SCHEMA
};
